---
name: shoe_mart
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=3.4.3 <4.0.0"
dependencies:
  build_runner: ^2.4.11
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  device_preview: ^1.2.0
  flutter:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_staggered_grid_view: ^0.4.0
  flutter_test:
    sdk: flutter
  fluttertoast: ^8.2.6
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  ionicons: ^0.2.2
  provider: ^6.1.2
flutter:
  uses-material-design: true
  assets:
    - assets/images/shoe_background_image.jpg
    - assets/images/adidas.png
    - assets/images/gucci.png
    - assets/images/jordan.png
    - assets/images/nike.png
    - assets/images/men_shoes_size_guide.png
    - assets/images/women_shoe_size_guide.png
    - assets/images/kids_shoe_size_guide.png
    - assets/images/top_image.png
    - assets/json/kids_shoes.json
    - assets/json/men_shoes.json
    - assets/json/women_shoes.json
